import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/include/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <metadata charset="UTF-8" />
        <metadata
          name="viewport"
          content="width=device-width initial-scale=1.0"
        />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
